package com.ai.assistance.operit.api.speech

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.InputStream

/**
 * Checks the Kotlin frontend against the NumPy oracle in
 * `tools/gigaam/reference_frontend.py`.
 *
 * The fixture is generated by `tools/gigaam/gen_fixture.py` from a fixed seed, so
 * both sides see byte-identical input without committing audio. If this test
 * fails, the model in `GigaAMRecognizer` will receive features it was never
 * trained on and return confident nonsense.
 */
class GigaAMFeatureExtractorTest {

    private fun resource(name: String): InputStream =
        requireNotNull(javaClass.classLoader?.getResourceAsStream("gigaam/$name")) {
            "missing test resource gigaam/$name — run tools/gigaam/gen_fixture.py"
        }

    @Test
    fun logMelMatchesNumpyReference() {
        val pcmBytes = resource("fixture.pcm").use { it.readBytes() }
        val pcm = GigaAMFeatureExtractor.decodePcm(pcmBytes, pcmBytes.size / 2)

        val actual = GigaAMFeatureExtractor.extract(pcm)

        val expected = resource("fixture_logmel.f32").use { it.readFloatArray() }

        val frames = GigaAMFeatureExtractor.frameCount(pcm.size)
        assertEquals(99, frames)
        assertEquals(64 * 99, actual.size)
        assertEquals(expected.size, actual.size)

        var worst = 0.0f
        var worstAt = -1
        for (i in expected.indices) {
            val delta = kotlin.math.abs(actual[i] - expected[i])
            if (delta > worst) {
                worst = delta
                worstAt = i
            }
        }
        // The oracle accumulates in float64 and the port in float32, so exact
        // equality is not available. 1e-3 is far below the gap a wrong n_fft,
        // a centred transform, or a 80-bin filterbank would produce.
        assertTrue(
            "log-mel diverges from the NumPy oracle by $worst at index $worstAt " +
                "(mel=${worstAt / 99}, frame=${worstAt % 99})",
            worst < 1e-3f
        )
    }

    @Test
    fun shortInputYieldsNoFrames() {
        assertEquals(0, GigaAMFeatureExtractor.frameCount(319))
        assertEquals(0, GigaAMFeatureExtractor.frameCount(0))
        assertEquals(1, GigaAMFeatureExtractor.frameCount(320))
        assertEquals(1, GigaAMFeatureExtractor.frameCount(479))
        assertEquals(2, GigaAMFeatureExtractor.frameCount(480))
        assertEquals(
            0,
            GigaAMFeatureExtractor.extract(ShortArray(319)).size
        )
    }

    @Test
    fun configConstantsComeFromTheModelYaml() {
        // If one of these changes the model stops accepting our features, so
        // pin them: multilingual_ctc.yaml says 64 / 320 / 160 / center false.
        assertEquals(64, GigaAMFeatureExtractor.N_MELS)
        assertEquals(320, GigaAMFeatureExtractor.WIN_LENGTH)
        assertEquals(160, GigaAMFeatureExtractor.HOP_LENGTH)
        assertEquals(320, GigaAMFeatureExtractor.N_FFT)
        assertEquals(false, GigaAMFeatureExtractor.CENTER)
        assertEquals(16000, GigaAMFeatureExtractor.SAMPLE_RATE)
    }
}

class GigaAMTokenVocabularyTest {

    private fun vocabulary(): GigaAMTokenVocabulary =
        javaClass.classLoader!!.getResourceAsStream("gigaam/tokens.txt")!!.use {
            GigaAMTokenVocabulary.parse(it)
        }

    @Test
    fun spaceIsZeroAndBlankIsLast() {
        val v = vocabulary()
        assertEquals(71, v.size)
        assertEquals(" ", v.symbol(0))
        assertEquals("<blk>", v.symbol(v.blankId))
        assertEquals(70, v.blankId)
    }

    @Test
    fun ctcBlanksAndRepeatsCollapse() {
        val v = vocabulary()
        // frames: 'a','a',blank,'b',blank,blank,'a' -> "aba"
        val vocabSize = v.size
        val frames = 7
        val logProbs = FloatArray(frames * vocabSize)
        fun put(frame: Int, id: Int) { logProbs[frame * vocabSize + id] = 10f }
        put(0, 2)  // a
        put(1, 2)  // a  -> collapses
        put(2, v.blankId)
        put(3, 3)  // b
        put(4, v.blankId)
        put(5, v.blankId)
        put(6, 2)  // a again after a blank -> emitted
        assertEquals("aba", v.greedyDecode(logProbs, frames, vocabSize))
    }

    @Test
    fun spaceTokenIsEmittedNotSkipped() {
        val v = vocabulary()
        val vocabSize = v.size
        // 'a', space, 'b' must yield "a b" — index 0 is the space character.
        val logProbs = FloatArray(3 * vocabSize)
        logProbs[0 * vocabSize + 2] = 10f
        logProbs[1 * vocabSize + 0] = 10f
        logProbs[2 * vocabSize + 3] = 10f
        assertEquals("a b", v.greedyDecode(logProbs, 3, vocabSize))
    }

    @Test
    fun allBlankDecodesToEmpty() {
        val v = vocabulary()
        val vocabSize = v.size
        val frames = 5
        val logProbs = FloatArray(frames * vocabSize)
        for (f in 0 until frames) logProbs[f * vocabSize + v.blankId] = 10f
        assertEquals("", v.greedyDecode(logProbs, frames, vocabSize))
    }

    @Test
    fun mismatchedClassCountIsRejected() {
        val v = vocabulary()
        val logProbs = FloatArray(10)
        val error = runCatching { v.greedyDecode(logProbs, 1, 10) }.exceptionOrNull()
        assertTrue(
            "expected a failure when the logit width does not match the vocabulary",
            error is IllegalArgumentException
        )
    }
}

private fun InputStream.readFloatArray(): FloatArray {
    val bytes = readBytes()
    require(bytes.size % 4 == 0) { "float32 fixture length ${bytes.size} is not a multiple of 4" }
    val buffer = java.nio.ByteBuffer.wrap(bytes).order(java.nio.ByteOrder.LITTLE_ENDIAN)
    val values = FloatArray(bytes.size / 4)
    for (i in values.indices) values[i] = buffer.float
    return values
}
