#!/usr/bin/env bash
# Run the GigaAM frontend tests without a full Gradle/Android build.
#
# The extractor, the vocabulary and their tests are plain JVM code — they import
# nothing from android.* — so they can be compiled and run with just a JDK and
# kotlinc. That matters because this checkout has no Android SDK, and a full
# assemble costs 20-40 minutes per iteration.
#
# The numerical fixture is generated by tools/gigaam/gen_fixture.py, which needs
# numpy. Re-run it only if that script changes.
#
# usage: tools/gigaam/run_port_tests.sh [work-dir]
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
work="${1:-/tmp/gigaam-port-tests}"
repo="$repo_root/app/src/main/java/com/ai/assistance/operit/api/speech"
tests="$repo_root/app/src/test/java/com/ai/assistance/operit/api/speech"
resources="$repo_root/app/src/test/resources"

: "${JAVA_HOME:?set JAVA_HOME to a JDK 17+ directory}"
kotlinc="${KOTLINC:-$HOME/kotlinc/bin/kotlinc}"
if [[ ! -x "$kotlinc" ]]; then
  echo "kotlinc not found at $kotlinc — set KOTLINC=/path/to/kotlinc/bin/kotlinc" >&2
  exit 2
fi

mkdir -p "$work/lib"
for spec in \
  "junit/junit/4.13.2/junit-4.13.2.jar:junit.jar" \
  "org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:hamcrest.jar"; do
  dest="$work/lib/${spec##*:}"
  [[ -f "$dest" ]] || curl -sSfL -o "$dest" "https://repo1.maven.org/maven2/${spec%%:*}"
done

rm -rf "$work/classes"
mkdir -p "$work/classes"
"$kotlinc" -nowarn \
  -cp "$work/lib/junit.jar:$work/lib/hamcrest.jar" \
  "$repo/GigaAMFeatureExtractor.kt" \
  "$repo/GigaAMTokenVocabulary.kt" \
  "$tests/GigaAMFeatureExtractorTest.kt" \
  -d "$work/classes"

kotlin_home="$(cd "$(dirname "$kotlinc")/.." && pwd)"
stdlib="$kotlin_home/lib/kotlin-stdlib.jar"
java_bin="$JAVA_HOME/bin/java"
[[ -x "$java_bin" ]] || { echo "java not found at $java_bin" >&2; exit 2; }

"$java_bin" -cp "$work/classes:$work/lib/junit.jar:$work/lib/hamcrest.jar:$resources:$stdlib" \
  org.junit.runner.JUnitCore \
  com.ai.assistance.operit.api.speech.GigaAMFeatureExtractorTest \
  com.ai.assistance.operit.api.speech.GigaAMTokenVocabularyTest